### ISSUE TITLE
Alternative for circle ci frontend tests

### ISSUE THREAD

**Issue by kesara** [ietf-tools/www#315]
The current Circle CI job runs a frontend test with the following command:
```
docker run --rm -e BASIC_AUTH=$BASIC_AUTH frontend yarn test $endpoint
```

The `$endpoint` can be either `https://www.ietf.org` or `https://wwwdev.ietf.org`.
This should be implemented in a way that it runs frontend tests on a locally hosted container.

**Comment by ghwood** [comment]
possibility consider accessibility as part of CI testing. See: https://github.com/ietf-tools/datatracker/issues/6119
