### ISSUE TITLE
implement a modern footer

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/www#377]
The footer currently contains a mix of links of different types, including links to affiliated sites, a link to a part of the main site, and a link to key legal information.

This mix of link types has no apparent organizational coherence, making expectations about what the viewer ought to find there or where the links will lead them. For example, it is unclear that “IRTF” leads to an entirely different website.

Also, the footer does not currently contain information and items that are commonly included in current webpage footer areas. Examples of these include copyright information, links to social media channels, and a summary version of a sitemap.

A modern approach to the footer section would allow for more of the commonly accepted links and information (social media and copyright), clearer organization of information and links, and greater context for links that would benefit from that.

A full specification for how this will be implemented is yet to be developed

**Comment by mgax** [comment]
We could implement a column-based footer, such as on the [Cloudflare website](https://www.cloudflare.com/en-gb/), with a StreamField editor, that allows creating columns, and links within columns. The links could either be external or internal, like in the Megamenu (https://github.com/ietf-tools/wagtail_website/pull/367). @ghwood would that provide the right editorial flexibility to organise the footer properly?

**Comment by mgax** [comment]
> Would it also be possible to have the kind of elements _below_ the stacked columns on the Cloudflare site?

Yep, sure, we can set up a list of links for that too.

**Comment by ghwood** [comment]
The Cloudflare model is good. Would it be helpful to have a more detailed specification?

**Comment by mgax** [comment]
> Would it be helpful to have a more detailed specification?

Here's a draft, based heavily on the Cloudflare website footer. Let me know if it matches your expectation and how you prefer to handle the optional bits.

#### Sections
Set up a content structure to edit footer sections. They will be displayed as columns.

Each section should have:
  - A _title_.
  - A list of links, with _title_, _page_ (reference to internal page) and _url_ fields. Exactly one of _page_ or _url_ may be set. Setting _url_ requires a _title_; setting _page_ will use the page's title, unless _title_ is also specified.

 For mobile viewports, the sections will be collapsed by default, and stacked vertically.

_(optional)_ On mobile, the first section is always expanded, to make its contents more visible.

#### Bottom links
Set up an additional list of links (same structure as the links in a section). They will be displayed below the sections.

_(optional)_ Move the social media links from the header to the footer, left-aligned, on the same line with the additional links. The various URLs can be configured at `/admin/settings/utils/socialmediasettings/` but are currently not specified.

_(optional)_ Add `© {year} IETF Administration LLC` at the start of the bottom links.

**Comment by ghwood** [comment]
@mgax Looking at the www.cloudflare.com footer as the example, this looks good to me. 

On the _(optional items)_, please do:
- handle mobile as described, and
- include the social media links on the same line as the bottom links
- do **not** add the © notice

Thank you!

**Comment by ghwood** [comment]
This works as expected on https://ws-modern-footer.dev.ietf.org, however the styling of footer column elements needs to be updated so that the line spacing between footer links that wrap and the footer links above/below are more clearly differentiated. Reducing the vertical spacing between wrapped lines would be my vote to try first. Rough mockup here to illustrate the idea. 
<img width="236" alt="image" src="https://github.com/ietf-tools/www/assets/5347540/acedd252-c7a6-4a19-9c3b-dfae76b70f03">
