### ISSUE TITLE
Test coverage upload to Codecov fails

### ISSUE THREAD

**Issue by mgax** [ietf-tools/www#394]
Since the repository was renamed (https://github.com/ietf-tools/www/issues/386), the Codecov upload action fails with the error message _Repository not found_: https://github.com/ietf-tools/www/actions/runs/8466201592/job/23194468418#step:7:35

Looking at the [repositories in Codecov](https://app.codecov.io/github/ietf-tools), `www` is not present, it might be necessary to click a "refresh" button in the Codecov UI.

**Comment by kesara** [comment]
This should work fine now.

**Comment by mgax** [comment]
It does, thanks!
