### ISSUE TITLE
Add a title to RSS feed.

### ISSUE THREAD

**Issue by kesara** [ietf-tools/www#405]
[IETF blog RSS feed](https://www.ietf.org/blog/feed) has an empty title.

**Comment by mgax** [comment]
The title, and description, for the RSS feed are configured in _Feed settings_ (/admin/settings/utils/feedsettings/). In my dump of the DB, from November 2023, they are empty, so I'm guessing they are also empty in the current production deployment. Configure them and the RSS feed should get a title.

I've submitted https://github.com/ietf-tools/www/pull/408 to generate specific feed titles for topics and authors.

**Comment by ghwood** [comment]
I've used the _Feed settings_ panel to configure Title and Description for the RSS feed. Thanks for the nudge.
